const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const {chromium}=require('playwright');
const root=process.env.CEDAR_STUDIO_URL||'http://127.0.0.1:4178/cedar-tv-updates/';
const out=process.env.CEDAR_STUDIO_ARTIFACTS||'../../tmp/studio-review/browser';
const fixture={collections:[{id:'fixture-group',title:'Cinema collection',folders:[{id:'scifi',title:'Science fiction',sources:[{id:'popular',title:'Popular science fiction',provider:'tmdb',tmdbSourceType:'DISCOVER',mediaType:'movie',filters:{withGenres:'878',voteCountGte:100}},{id:'rated',title:'Top rated',provider:'tmdb',tmdbSourceType:'TOP_RATED',mediaType:'movie'},{id:'unsupported',title:'Unsupported recommendations',provider:'addon',addonId:'aio',catalogId:'trakt.recommendations.movies'}]},{id:'drama',title:'Drama',sources:[{id:'drama-source',title:'Drama movies',provider:'tmdb',tmdbSourceType:'DISCOVER',mediaType:'movie',filters:{withGenres:'18'}}]}]}]};
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});try{const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(root+'customize/');await p.locator('#home-outline li').first().waitFor();assert.equal(await p.locator('#home-outline li').count(),3);assert.equal(await p.locator('#home-preview .poster-rail').count(),3);assert.ok(!await p.locator('body').innerText().then(s=>s.includes('Folder symbol')));
await p.getByRole('button',{name:'Move Top rated movies up',exact:true}).click();assert.deepEqual(await p.locator('.outline-select strong').allTextContents(),['Trending movies','Top rated movies','Popular movies']);await p.getByRole('textbox',{name:'Branch title',exact:true}).fill('My trending');await p.getByRole('textbox',{name:'Branch title',exact:true}).press('Tab');assert.equal(await p.locator('.outline-select strong').first().innerText(),'My trending');await p.reload();assert.equal(await p.locator('.outline-select strong').first().innerText(),'My trending');
await p.locator('#export').click();let download=p.waitForEvent('download');await p.locator('#download-export').click();let file=await download;await file.saveAs(out+'/direct-export.json');let data=JSON.parse(await fs.readFile(out+'/direct-export.json'));assert.equal(data.config.collections.length,0);assert.deepEqual(data.config.home_order.map(x=>x.id),['trending_movies','top_rated_movies','popular_movies']);
await p.locator('#open-import').click();await p.locator('#import-file').setInputFiles({name:'collection.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await p.locator('#import-review').waitFor();assert.equal(await p.locator('#home-outline li').count(),3);assert.match(await p.locator('#issue-summary').innerText(),/1 compatibility/);await p.locator('#import-none').click();assert.equal(await p.locator('#apply-import').isDisabled(),true);await p.locator('#import-all').click();await p.locator('#apply-import').click();assert.equal(await p.locator('#home-outline li').count(),4);await p.getByRole('button',{name:'Cinema collection Branch Group · 2 branches',exact:true}).click();await p.getByLabel('Appearance scope').selectOption('phone');await p.getByLabel('Home row',{exact:true}).selectOption('classic');assert.match(await p.locator('#save-state').innerText(),/Saved/);await p.getByLabel('Preview device').selectOption('phone');assert.equal(await p.locator('#home-preview').getAttribute('data-device'),'phone');await p.locator('.branch-card summary').first().click();await p.getByRole('checkbox',{name:'Include source Top rated',exact:true}).uncheck();await p.locator('.source-line').filter({hasText:'Popular science fiction'}).getByRole('button',{name:'Edit',exact:true}).click();await p.locator('#source-title').fill('Sci-fi discoveries');await p.locator('#source-filter-details summary').click();await p.locator('#source-year').fill('2020');await p.locator('#source-form button[type=submit]').click();assert.match(await p.locator('#branch-content').innerText(),/Sci-fi discoveries/);
await p.getByLabel('Browse branches',{exact:true}).selectOption('chips-and-grid');await p.locator('#home-preview .group-card').first().click();assert.equal(await p.locator('#home-preview .poster-grid').count(),1);await p.getByRole('button',{name:'← Home',exact:true}).click();await p.locator('#export').click();assert.match(await p.locator('#export-note-count').innerText(),/1 compatibility/);download=p.waitForEvent('download');await p.locator('#download-export').click();file=await download;await file.saveAs(out+'/group-export.json');data=JSON.parse(await fs.readFile(out+'/group-export.json'));assert.equal(data.config.collections[0].folders[0].sources.length,1);assert.equal(data.config.collections[0].folders[0].sources[0].filters.year,2020);assert.equal(data.config.collections[0].folders[0].sources[0].filters.voteCountGte,100);assert.equal(data.config.collections[0].cedarLayout.overrides.phone.rowStyle,'classic');assert.ok(!JSON.stringify(data).includes('coverEmoji'));
await p.locator('#open-import').click();await p.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.waitForFunction(()=>document.getElementById('import-status').textContent.includes('not valid JSON'));assert.match(await p.locator('#import-status').innerText(),/not valid JSON/);assert.equal(await p.locator('#home-outline li').count(),4);await p.locator('#import-file').setInputFiles({name:'collection.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await p.locator('#import-mode').selectOption('replace');await p.locator('#apply-import').click();assert.equal(await p.locator('#home-outline li').count(),1);await p.locator('#undo').click();assert.equal(await p.locator('#home-outline li').count(),4);
await p.getByRole('button',{name:'Quick editor',exact:true}).click();assert.equal(await p.locator('#quick-editor .check-row').count(),4);await p.getByRole('button',{name:'Home preview',exact:true}).click();await p.locator('#preview-device').selectOption('television');await p.locator('[data-theme-select]').selectOption('dark');await p.screenshot({path:out+'/home-dark.png',fullPage:true});await p.locator('[data-theme-select]').selectOption('light');await p.screenshot({path:out+'/home-light.png',fullPage:true});
await p.locator('#avatars').click();await p.locator('.avatar-card').first().waitFor();await p.locator('#avatar-search').fill('bluey');assert.ok(await p.locator('.avatar-card').count()>0);await p.locator('.avatar-card').first().click();await p.getByRole('button',{name:'Copy avatar URL'}).click();assert.match(await p.evaluate(()=>navigator.clipboard.readText()),/\/avatars\//);await p.locator('#badges').click();await p.locator('.badge-card').first().waitFor();await p.locator('#badge-search').fill('Aurora');assert.equal(await p.locator('.badge-card').count(),1);
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});for(const hash of ['collections','avatars','badges']){await p.goto(root+'customize/#'+hash);await p.locator('#'+hash+'-panel').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width} overflow ${hash}`);if(width===390&&hash==='collections')await p.screenshot({path:out+'/mobile.png',fullPage:true});}}
assert.deepEqual(errors,[]);console.log('Browser checks passed: Branch Home, ordering, title edit, persistence, direct export, collection review, source edits, device layout, compatibility report, replace/undo, invalid import, quick editor, galleries, light/dark and 12 viewport checks.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
